apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-stg
  namespace: argocd
  # Enable cascading deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: App of apps for stg env
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'