apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    # Reference cluster (in-cluster)
    server: https://kubernetes.default.svc 
  project: project-dev
  source:
    # Specify path to your application configs
    path: environments/dev/applications
    repoURL: https://github.com/yreinhardt/argocd-app-of-apps-pattern.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true